<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <#include "./head.ftlh">
</head>
<body>
<div class="container">

                <div>Hi</div>

                <div>You can`t go further without signing up/on</div>

                <div> <a href="/signUp"><button type="submit" class="btn btn-primary">Sign Up</button></a></div>

                <div> <a href="/signIn"><button type="submit" class="btn btn-primary">Sign In</button></a></div>
</div>
</body>
</html>